using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KSALVL
{
    public class Objects
    {
        public Dictionary<string, string[]> ObjectList = new Dictionary<string, string[]>()
        {
            {"StartPortal", new string[] {"int wuid", "int x", "int y", "string dir", "int helperNo", "string kind", "int portalNo", "string variation"} },
            {"BGAltarCtrl", new string[] {"int wuid", "int x", "int y", "bool isInitOpenFlower", "string kind"} },
            {"DimensionHole", new string[] {"int wuid", "int x", "int y", "int holeID", "bool isSaveBetweenStep", "string kind", "float scale", "string variation"} },
            {"AreaDollyCamera", new string[] {"int wuid", "int x", "int y", "bool bootBySignal", "int expand", "string intpType", "string kind", "int offsetX", "int offsetY", "string shutdownKind", "int signalNo", "int signalNoShutdown", "int targetObj"} },
            {"RippleField", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"DoorAbility", new string[] {"int wuid", "int x", "int y", "string abilityKind", "string decorationKind", "string kind", "int portalNo", "int signalNo", "int stepShift"} },
            {"MoveLandController", new string[] {"int wuid", "int x", "int y", "float accelRate", "string dummy", "string effectKind", "int firstWaitFrame", "string groupIndex", "bool isBreakBlock", "bool isSaveBetweenStep", "string kind", "string loopKind", "int moveFrame", "float moveSpeed", "string path", "int postWaitFrame", "int prevWaitFrame", "string property", "int signalNo", "string speedKind", "string startKind", "bool useSmoke"} },
            {"MoveLandPathNode", new string[] {"int wuid", "int x", "int y", "float accelRate", "bool isOffsetNode", "bool isUsed", "string kind", "int moveFrame", "float moveSpeed", "int postWaitFrame", "int prevWaitFrame", "int signalNo", "string speedKind"} },
            {"WorldCameraLock", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"FieldEffect", new string[] {"int wuid", "int x", "int y", "string kind", "string subKind"} },
            {"EnemyGenerator", new string[] {"int wuid", "int x", "int y", "int helperCount", "bool isFirstGenerateVariation", "string kind", "int targetObj"} },
            {"Switch", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isSendInfoContinue", "bool isTargetAI", "string kind", "int signalNo", "string variation"} },
            {"AIPursuitCloseZone", new string[] {"int wuid", "int x", "int y", "int endSignalNo", "bool isSaveBetweenStep", "string kind", "int startSignalNo"} },
            {"ZoneSwitch", new string[] {"int wuid", "int x", "int y", "int activateSignalNo", "bool is1POnly", "bool isNoReactInvisibleHero", "bool isSendInfoContinue", "string kind", "int returnFrame", "int signalNo", "string variation"} },
            {"GuideBoard", new string[] {"int wuid", "int x", "int y", "int appearWaitFrame", "string helperKind", "bool isUseSuccessArea", "string kind", "int signalNo", "string subKind", "int targetObj", "string twinkleKind"} },
            {"GuideBoardAbilityIcon", new string[] {"int wuid", "int x", "int y", "int appearStopperSignalNo", "int appearWaitFrame", "string iconGroupA", "string iconGroupB", "string iconKindA", "string iconKindB", "bool isHideOnExecutiveDeGo", "bool isSaveBetweenStep", "bool isSingle", "bool isVisibleArrow", "string kind", "int signalNo", "int targetObj"} },
            {"Slate", new string[] {"int wuid", "int x", "int y", "string charaKind", "bool isConstraintMoveLand", "string kind", "float posOffsetZ", "float rotDegX", "float rotDegY", "float rotDegZ", "float scale"} },
            {"ArrowBoard", new string[] {"int wuid", "int x", "int y", "string arrowDir", "string kind"} },
            {"FuseCannonMini", new string[] {"int wuid", "int x", "int y", "bool doMove", "string kind", "int portalNo", "int signalNo", "int stepShift"} },
            {"FuseGenerator", new string[] {"int wuid", "int x", "int y", "bool isAttackAI", "bool isNeedBegin", "string kind", "string path", "string subKind"} },
            {"FusePathNode", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "string kind", "string path0", "string path1", "int signalNo", "string subKind"} },
            {"MassWaddledeeFromFar", new string[] {"int wuid", "int x", "int y", "int diameter", "bool isRelayOffs0Valid", "bool isRelayOffs1Valid", "bool isRelayOffs2Valid", "bool isRelayOffs3Valid", "bool isRelayOffs4Valid", "string kind", "float relayOffs0X", "float relayOffs0Y", "float relayOffs0Z", "float relayOffs1X", "float relayOffs1Y", "float relayOffs1Z", "float relayOffs2X", "float relayOffs2Y", "float relayOffs2Z", "float relayOffs3X", "float relayOffs3Y", "float relayOffs3Z", "float relayOffs4X", "float relayOffs4Y", "float relayOffs4Z", "string variation"} },
            {"Block", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind", "string subKind"} },
            {"BlockBreakWatcher", new string[] {"int wuid", "int x", "int y", "string kind", "int signalNo"} },
            {"BlockRegenerateCtrl", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"Door", new string[] {"int wuid", "int x", "int y", "int appearFrame", "string decorationKind", "int doorID", "bool isHelperGoOnly", "bool isHideFirst", "bool isMoveLandConstraint", "bool isSaveBetweenStep", "string kind", "int portalNo", "int signalNo", "int stepShift"} },
            {"MassWaddledee", new string[] {"int wuid", "int x", "int y", "int diameter", "string dir", "bool generateItemBox", "bool isAccelByDistance", "string itemDropKind", "string kind", "int signalNo", "float speed", "string variation"} },
            {"ChainStarter", new string[] {"int wuid", "int x", "int y", "int delay", "string kind", "int signalNo"} },
            {"AirFlow", new string[] {"int wuid", "int x", "int y", "string dir", "bool isUseSignal", "string kind", "string level", "string signalModeKind", "int signalNo", "string variation"} },
            {"StakeBattery", new string[] {"int wuid", "int x", "int y", "int electrifySignalNo", "bool isAttackAI", "bool isColorSwap", "bool isNeedBegin", "bool isSaveBetweenStep", "string kind", "int offAIAttackSignalNo", "int onAIAttackSignalNo", "string path", "string subKind"} },
            {"Shutter", new string[] {"int wuid", "int x", "int y", "bool isOnce", "bool isOpenStart", "bool isReturn", "bool isSaveBetweenStep", "string kind", "int openWaitFrame", "int returnFrame", "int signalNo", "string subKind"} },
            {"Stake", new string[] {"int wuid", "int x", "int y", "bool isAttackAI", "bool isSaveBetweenStep", "string kind", "int signalNo", "string variation"} },
            {"ChainConnector", new string[] {"int wuid", "int x", "int y", "int bombCount", "string kind", "int targetID"} },
            {"AIReaction", new string[] {"int wuid", "int x", "int y", "int actionSignalNo", "bool isSaveBetweenStep", "string kind", "string path", "int signalNo", "string variation"} },
            {"RoomGuarder", new string[] {"int wuid", "int x", "int y", "int bgmChangeSignalDelay", "int bgmChangeSignalNo", "string bgmKind", "int cameraExpand", "bool isNotChangeBGM", "string kind", "string mode", "int roomGuarderID", "int signalNo", "string validMode"} },
            {"RoomGuarderPoint", new string[] {"int wuid", "int x", "int y", "string kind", "int roomGuarderID", "int roomGuarderPointID"} },
            {"RoomGuarderEnemyList", new string[] {"int wuid", "int x", "int y", "int firstWaitTime", "bool isLoopStartingPoint", "string kind", "int maxGeneratedNum", "int roomGuarderID", "int roomGuarderPointID", "int signalNo", "int timeInterval", "bool useNextEnemyListIDArray", "bool useRoomGuarderPointID"} },
            {"LockShutter", new string[] {"int wuid", "int x", "int y", "string kind", "string lockColor", "int signalNo"} },
            {"FriendActionPedestal", new string[] {"int wuid", "int x", "int y", "string dir", "bool isDemo", "bool isJointForce", "bool isStepIn", "string kind", "int portalNo", "int signalNo", "string subKind"} },
            {"FriendBridgeTargetPoint", new string[] {"int wuid", "int x", "int y", "string dir", "string kind", "int signalNo", "string variation"} },
            {"FriendBridgeControler", new string[] {"int wuid", "int x", "int y", "bool isMoveCamera", "string kind", "int signalNo"} },
            {"CannonBlow", new string[] {"int wuid", "int x", "int y", "string dirType", "bool doMoveStep", "bool isClockwise", "string kind", "int portalNo", "string rotateSpeed", "string rotateVariation", "int stepShift", "int targetObj", "string variation"} },
            {"FriendBridgePole", new string[] {"int wuid", "int x", "int y", "string kind", "string length", "int signalNo"} },
            {"HangSwitch", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind", "int signalNo", "string variation"} },
            {"ItemBox", new string[] {"int wuid", "int x", "int y", "string kind", "bool multiItemMode"} },
            {"AIForbidAttackZone", new string[] {"int wuid", "int x", "int y", "bool invalidInHelperGo", "string kind"} },
            {"AbilitySeat", new string[] {"int wuid", "int x", "int y", "string abilityKind", "bool isSaveBetweenStep", "string kind", "int signalNo", "string variation"} },
            {"AreaBGMFadeOut", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"WaterFlow", new string[] {"int wuid", "int x", "int y", "string dir", "int groupId", "string kind", "string level", "string validRange"} },
            {"FireBox", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind"} },
            {"CutRope", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind", "int length", "int signalNo"} },
            {"AISearchIgnoreZone", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"StakeIce", new string[] {"int wuid", "int x", "int y", "bool isAttackAI", "bool isSaveBetweenStep", "string kind", "int signalNo", "string variation"} },
            {"FriendActionMove", new string[] {"int wuid", "int x", "int y", "string kind", "int portalNo", "int stepShift"} },
            {"BreakableLandCtrl", new string[] {"int wuid", "int x", "int y", "bool isBlownApart", "bool isSaveBetweenStep", "string kind", "int signalNo"} },
            {"FriendActionFitWall", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"FriendActionGoal", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"WhiteBoard", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"RopeBomb", new string[] {"int wuid", "int x", "int y", "bool isNotAbleToSupply", "bool isSendSignalWithBurnCut", "bool isTargetAI", "bool isUseFallEndEffect", "string kind", "string rollOutType", "int signalNo", "int signalNoWhenBurnCut", "string size", "string successSE"} },
            {"FuseDynamite", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "string kind", "int signalNo"} },
            {"FuseWater", new string[] {"int wuid", "int x", "int y", "int height", "bool isAttackAI", "string kind"} },
            {"CutRopeStepHard", new string[] {"int wuid", "int x", "int y", "bool isAttackAI", "bool isSaveBetweenStep", "string kind", "int ropeLength", "string variation"} },
            {"ItemRegenerateCtrl", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"FallenLeaves", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "string kind"} },
            {"CutChainBurning", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind", "int length", "int signalNo"} },
            {"BigMeteor", new string[] {"int wuid", "int x", "int y", "string dir", "string distance", "string kind", "int signalNo", "string size", "float speed", "string variation", "int waitFrame"} },
            {"GiantRollingBlade", new string[] {"int wuid", "int x", "int y", "string bladeVariation0", "string bladeVariation1", "string bladeVariation2", "string bladeVariation3", "bool isClockwise", "bool isConstraintItem", "string kind", "string variation"} },
            {"AreaLock", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"AreaLockThrough", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"TwinkleStarEndDemo", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"ExecutivesEndDemo", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"DoorGoal", new string[] {"int wuid", "int x", "int y", "int doorID", "bool isMoveLandConstraint", "string kind", "int signalNo"} },
            {"SwitchBig", new string[] {"int wuid", "int x", "int y", "string helperGoLastItem", "string helperGoLastItem2", "string kind", "bool noReaction", "int signalNo", "string subKind"} },
            {"HelperGoItemHelperExclusive", new string[] {"int wuid", "int x", "int y", "string helperKind1", "string helperKind10", "string helperKind2", "string helperKind3", "string helperKind4", "string helperKind5", "string helperKind6", "string helperKind7", "string helperKind8", "string helperKind9", "bool isReverse", "string kind"} },
            {"PopFlower", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"GrassyPlace", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "string kind", "string subKind"} },
            {"AreaBGMChange", new string[] {"int wuid", "int x", "int y", "bool isActivateByHeroPos", "string kind", "string variation"} },
            {"AIAttackPointForCook", new string[] {"int wuid", "int x", "int y", "int endSignalNo", "bool isSaveBetweenStep", "string kind", "int startSignalNo"} },
            {"MovingSawBody", new string[] {"int wuid", "int x", "int y", "int advanceFrame", "string initDirType", "bool isAntiClockwise", "bool isAttackAI", "bool isBreakableInLand", "bool isHelperAICloseMode", "string kind", "int moveFrame", "int postWaitFrame", "int preWaitFrame", "string repeatType", "int signalNo", "int spawnInterval", "string startType", "string variation", "float velocity"} },
            {"MovingSawRail", new string[] {"int wuid", "int x", "int y", "string kind", "string path"} },
            {"MovingSawRailNode", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"AIAttackPoint", new string[] {"int wuid", "int x", "int y", "string ability1", "string ability2", "string ability3", "string ability4", "string dir", "string element", "bool isLandPenetrate", "bool isSaveBetweenStep", "string kind", "int signalNo", "int stopSignalNo", "string variation"} },
            {"SwitchWindmill", new string[] {"int wuid", "int x", "int y", "bool isSaveBetweenStep", "bool isTargetAI", "string kind", "int signalNo", "string variation"} },
            {"OGenMarginExpander", new string[] {"int wuid", "int x", "int y", "string kind", "int targetUniqueId"} },
            {"GuideBoardFriendAction", new string[] {"int wuid", "int x", "int y", "string kind", "int signalNo", "int targetObj", "string variation"} },
            {"HelperGoItemExcluder", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"FriendActionDead", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"HelperGoEnemyListHelperExclusive", new string[] {"int wuid", "int x", "int y", "string helperKind1", "string helperKind10", "string helperKind11", "string helperKind12", "string helperKind13", "string helperKind14", "string helperKind15", "string helperKind16", "string helperKind17", "string helperKind18", "string helperKind19", "string helperKind2", "string helperKind20", "string helperKind3", "string helperKind4", "string helperKind5", "string helperKind6", "string helperKind7", "string helperKind8", "string helperKind9", "string kind"} },
            {"BlockAIReactionZone", new string[] {"int wuid", "int x", "int y", "string kind", "float orderHalfHeight", "float orderHalfWidth", "string variation"} },
            {"ResetAbilitySeat", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"SecretPath", new string[] {"int wuid", "int x", "int y", "string kind", "string modelKind", "float posOffsetZ"} },
            {"EscapeEvent", new string[] {"int wuid", "int x", "int y", "bool isNoBgm", "string kind", "int portalNo", "int signalNo"} },
            {"GoldKirbyStatue", new string[] {"int wuid", "int x", "int y", "int doorID", "int infoDelay", "bool isStageClear", "int itemInterval", "string kind", "int portalNo", "int signalNo", "int stepShift"} },
            {"RockForMultiCannon", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"AreaRotationCamera", new string[] {"int wuid", "int x", "int y", "string intpType", "string kind", "int rotateX", "int rotateY", "int rotateZ", "int targetObj"} },
            {"ArenaStepEnd", new string[] {"int wuid", "int x", "int y", "string kind", "int signalNo"} },
            {"PonKonGimmick", new string[] {"int wuid", "int x", "int y", "string floortype", "string kind", "string variation"} },
            {"ArenaRestStation", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"AICantGetItemZone", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"CreditManager", new string[] {"int wuid", "int x", "int y", "string kind", "string subKind"} },
            {"CreditItemCtrl", new string[] {"int wuid", "int x", "int y", "bool isEnabled0", "bool isEnabled1", "bool isEnabled2", "bool isEnabled3", "bool isEnabled4", "string kind"} },
            {"EndingDemo", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"StandLight", new string[] {"int wuid", "int x", "int y", "string kind", "string subKind"} },
            {"BgShaderParamChanger", new string[] {"int wuid", "int x", "int y", "string key1", "string kind", "float value1"} },
            {"FriendRodDemoLocator", new string[] {"int wuid", "int x", "int y", "int index", "string kind"} },
            {"MuseumFirstDemo", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"DreamRodGenLocator", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"ForbidRegenerateEnemy", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"KibidangoDemo", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"CorkPlug", new string[] {"int wuid", "int x", "int y", "int itemCountFood1", "int itemCountFood2", "int itemCountPointStarBlue", "int itemCountPointStarGreen", "int itemCountPointStarRed", "string kind", "bool removePointStarYellow", "string subKind"} },
            {"FruitTree", new string[] {"int wuid", "int x", "int y", "float heightScale", "bool isRed", "string kind", "float rotation", "bool useCustomHeightScale", "bool useCustomRotation"} },
            {"AreaBlendCamera", new string[] {"int wuid", "int x", "int y", "int blendRange", "int endSignalNo", "bool isBlendD", "bool isBlendL", "bool isBlendR", "bool isBlendU", "bool isSaveBetweenStep", "string kind", "int targetObj"} },
            {"FriendCopyFirstDemo", new string[] {"int wuid", "int x", "int y", "bool invalidInHelperGo", "string kind", "int targetObj"} },
            {"HelperGoPutItemOnNeedlessDoor", new string[] {"int wuid", "int x", "int y", "int correspondedDoorID", "string kind"} },
            {"DoorMulti", new string[] {"int wuid", "int x", "int y", "int charaNumForOpen", "string kind", "int portalNo", "int signalNo", "int stepShift"} },
            {"CameraHeightLimitUnsetter", new string[] {"int wuid", "int x", "int y", "bool isForbidSpaceJump", "string kind"} },
            {"CutChainStep", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"ItemAIReactionZone", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"AIReactionPathNode", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"EscapeEventEnemyGenerator", new string[] {"int wuid", "int x", "int y", "bool isPriorCreateInitHelper", "string kind"} },
            {"TwinkleStarEscapeEvent", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"TwinkleStarBGMChanger", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"BigBomb", new string[] {"int wuid", "int x", "int y", "string kind"} },
            {"DarkHeart", new string[] {"int wuid", "int x", "int y", "string kind", "string variation"} },
            {"LastCloseContest", new string[] {"int wuid", "int x", "int y", "string kind"} }
        };
        public Dictionary<string, string[]> ItemList = new Dictionary<string, string[]>()
        {
            {"PointStarYellow", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"PointStarGreen", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"PointStarRed", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"PointStarBlue", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"OneUp", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"MTomato", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"Food", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string subKind", "string variation" } },
            {"IllustPiece", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"IllustPieceRare", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"IllustPieceRareGray", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"InvincibleCandy", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"GenkiDrink", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"DreamRod", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"FriendPower", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"FriendDefense", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"FriendSpeed", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"AllUp", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"AdcHeart", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"AdcHeartGray", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"None", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"CopySource", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"AbilitySeatItem", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"ArtistPainterFood", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"CookFood", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"CherryMadeInArena", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"TomatoMadeInArena", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"IllustPieceNfp", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } },
            {"FoodHQ", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string itemCategory", "string kind", "string variation" } }
        };
        public Dictionary<string, string[]> BossList = new Dictionary<string, string[]>()
        {
            {"Whispywoods", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string modelKind", "string size", "string variation"} },
            {"Kracko", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"MetaKnight", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Kingdedede", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"ExecutiveThunder", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string modelKind", "string size", "string variation"} },
            {"Hiness", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"PonKon", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string modelKind", "string size", "string variation"} },
            {"ExecutiveIce", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"ExecutiveFire", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"BKnight", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"LastBoss", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string modelKind", "string size", "string variation"} },
            {"Giantironmom", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
        };
        public Dictionary<string, string[]> MBossList = new Dictionary<string, string[]>()
        {
            {"Bonkers",new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string modelKind", "string size", "string variation" } },
            {"Bugzzy",new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string modelKind", "string size", "string variation" } },
            {"ChefKawasaki",new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string modelKind", "string size", "string variation" } },
            {"Misterfrosty",new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string modelKind", "string size", "string variation" } },
            {"Vivitia", new string[] { "int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string modelKind", "string size", "string variation" } },
            {"Marx", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
        };
        public Dictionary<string, string[]> EnemyList = new Dictionary<string, string[]>()
        {
            {"Poppybrosjr", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Waddledee", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Brontoburt", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Bouncy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Burningleo", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Puppetdee", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"FloatSlime", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Waddledoo", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"WaterEnemy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Kabu", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"ShieldEnemy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string depend", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string mapDBKind", "string size", "string variation"} },
            {"Dekabu", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Broomhatter", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Chip", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Nruff", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Wonkey", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Chilly", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Sirkibble", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Scarfy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Shotzo", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Cappy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Gordo", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Coner", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Blipper", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Glunk", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Mamatee", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Squishy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Gim", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Nesp", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Rocky", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"StickEnemy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Beetlie", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"BioSpark", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Noddy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Propeller", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Como", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Wester", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Bomber", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"BigBouncy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Bladeknight", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Gabon", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Jaharbeliever", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Knucklejoe", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Grizzo", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Birdon", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Conce", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"TwoFace", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"MaskEnemy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"FestivalEnemy", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },
            {"Walky", new string[] {"int wuid", "int x", "int y", "string constraintMoveGroup", "string dirType", "string enemyCategory", "int group", "string kind", "string level", "string size", "string variation"} },            
        };
    }
}
